language: node_js
node_js:
- node
services:
- mongodb
cache:
  yarn: true
before_script:
- yarn build
deploy:
  provider: openshift
  user: daniel@danielchao.me
  password:
    secure: NvACBS8wDxEmFb1yDG0pYFN3EO9ycr7TI+cwuS4Bd8AE1Nn/71Ol/mm11DpY1acOVMVFPcNF05NJ8DDVqqGIucmIjln6BXVZ7Y8wJB2Wuug6sRfVj26QK8eTRjy0FWO20oKlQ9lCRtIOId7NPXoSKDk9khxPsCFtiEMeYLefDj4s3YZYknOwqbvju4kHcJZZaD5o47bL8LBIz+ALOvjuQSjvgm48MARsADWAr6VPy9y+66S7kht3rwjW+1d0naUCHdxyUYiTVFvWC2Zs/dHMbqKGAWNHXEGaD9mqgxJtXUzqqHjpbcgXSgtqw/89p7foMqJigQaBmZjs4x+NqrrpkKQll0ibqIFItauJa1ID1ODHxRfhONYILR9ivORIE9FUbq6Jc+CeTdCINshVoe6DbOQP3sWnFbT1JGDC+vnyon7tNiu1SF80VeR9OXxE2kzhHYnStJlK0Pr/+9gRbf/j2MaacsyTFKvaAWdwXjMaqIkVj7LlLa3pf5cFZuAFU73dafWM/5bGr8UN17OeSxdB7GjY12dDHdCFAP3iRa6W84DA8Z4ov0UaiwDPJ6oq4XP+sW13rJ0qXkcvmM8Q6F1QDP3QsvLKsC3EHz0BmQj1BZinz5kVztYjB1c7WiwZra6R2qw1heFayVdnsBL9NhKcn0cf4xe+UdNbi71qFB8zEC4=
  app: sunfile
  domain: danielchao.rhcloud.com
  on:
    repo: dchao19/sunfile-backend
