language: node_js
node_js:
- node
services:
- mongodb
cache:
  yarn: true
before_script:
- yarn build
before_deploy:
- git fetch --unshallow
deploy:
  provider: heroku
  app: sunfile-v3-production
  api_key:
    secure: cK3fh84SrHHsqgZ/TKPhPOIyjqKl8z7I+ELM/DSBaQw6iQPVq/c1a/x4PLegwP9fGwyAMiLRGSkapOUxg5Aqy+uRJOvtTGajTxgh8B3bl3HuvJigSy+OWzGnHjoobajOuMqe6D6rID/tenqZ3BZJYAs/nvkZDKJJtk4/613Gxti6e3qK2GAb2REQ0qxfOg4ogvwPhyIPlTFTlJChqbz4R24zHZ12FtVN3SiLgSPVtJ8ToWevueE8YvAuP3AD0rIYy96FFo6ycKBSvCNKtk3FqCYUtAE78DWl7e1NiYuGVYApAdRIxYhNVF1858JO1ONS0ihumLEzVKWVR66HAkFQ6gT/QMO2+luwluGizpSE+U7otsaRPazsjdkCdhwJxg84acVhifWL+BZLg+eC72o7X5zsxmhn0BpcCD0QPAjcqNKwUFdMG++7hSPYZ6H1jsDMazRNvZmH4e1eWoSYcftFxFbZGHJkAYeJ+JH3WXKwBiflPyX4WNUl456fLOCgcd8kx8sdAsrpItTmI2/eMtb6iEpTCJRAR9vMrtnr72NqNE7xGa8CltraMhhpGYfUJ09Hws+R+kXSWhH4sXQD4JoJhJAPKulKx/C9j5w5ZDqxd/QQ+GstU8NzNxJbD+FYkDGuM5JXslmwW1Fy4j8tuDCUrCNo3jAZXzzY0wPac3h0DLE=
