var utils = {
    generateRandomTeamCode: function (){
        var selectables = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        var teamCode = "";
        for (var i = 0; i < 6; i++) {
            teamCode += selectables.charAt(Math.floor(Math.random() * 35));
        }
        return teamCode;
    },
    sources: {
      nytimes:  "NYT",
      brookings:  "Brk",
      worldpoliticsreview:  "WPR",
      "ap.org":  "AP",
      carnegie:  "CE",
      foreignpolicy:  "FP",
      diplomat:  "Dpl",
      foreignaffairs:  "FA",
      hir:  "HIR",
      harvardpolitics:  "HPR",
      politico:  "Pol",
      reuters:  "Rt",
      wsj:  "WSJ",
      mercopress:  "MP",
      economist:  "Eco",
      moscowtimes:  "MT",
      heritage:  "HF",
      cnn:  "CNN",
      csis:  "CS",
      aljazeera:  "AJ",
      cfr:  "CFR",
      "blogs.state.gov":  "DPN",
      theatlantic:  "Atl",
      washingtonpost:  "WP",
      usatoday:  "USAT",
      thehill:  "H",
      chathamhouse:  "CH",
      bbc:  "BBC",
      npr:  "NPR",
      businessinsider:  "BI",
      andina:  "AN",
      laht:  "LH",
      businessweek:  "Blm",
      usip:  "IP",
      newsweek:  "Nw",
      alhayat:  "AH",
      japantimes:  "JT",
      defensenews:  "DN",
      bloomberg: "Blm",
      amnesty: "Am",
      pewresearch: "PRC" ,
      piie: "PI",
      csmonitor: "CSM"     
	},

	sourcesFullName: {
      nytimes:  "New York Times",
      brookings:  "Brookings Institute",
      worldpoliticsreview:  "World Politics Review",
      "ap.org":  "Associated Press",
      carnegie:  "Carnegie Endowment for International Peace",
      foreignpolicy:  "Foreign Policy Magazine",
      diplomat:  "The Diplomat",
      foreignaffairs:  "Foreign Affairs",
      hir:  "Harvard International Review",
      harvardpolitics:  "Harvard Politics Review",
      politico:  "Politico",
      reuters:  "Reuters Wire Service",
      wsj:  "Wall Street Journal",
      mercopress:  "MercoPress",
      economist:  "The Economist",
      moscowtimes:  "Moscow Times",
      heritage:  "The Heritage Foundation",
      cnn:  "CNN",
      csis:  "Center for Strategic and International Studies",
      aljazeera:  "Al Jazeera America",
      cfr:  "Council for Foreign Relations",
      "blogs.state.gov":  "U.S. Secretary of State Official Blog (DipNote)",
      theatlantic:  "The Atlantic",
      washingtonpost:  "The Washington Post",
      usatoday:  "USA Today",
      thehill:  "The Hill",
      chathamhouse:  "Chatham House (The Royal Institute of International Affairs)",
      bbc:  "BBC",
      npr:  "National Public Radio",
      businessinsider:  "Business Insider",
      andina:  "AN",
      laht:  "Latin American Herald Tribune",
      businessweek:  "Bloomberg Businessweek",
      usip:  "United States Institute of Peace",
      newsweek:  "Newsweek",
      alhayat:  "AH",
      japantimes:  "Japan Times",
      defensenews:  "Defense News",
      bloomberg: "Bloomberg",
      amnest: "Amnesty International",
      pewresearch: "Pew Research Center",
      piie: "Peterson Institute for International Economics",
      csmonitor: "Christian Science Monitor"
	}
}

module.exports = utils;